### ISSUE TITLE
I like it

### ISSUE THREAD

**Issue by vsraptor** [Pan-ML/panml#38]
The more I read the docs of this library the more I like it :)

Initially I thought it is based on LangChain (which I started to learn), but I see PanML is self hosted and it seem simpler to use/start-doing-things.

1. Can you do quick Pro vs Cons list.
2. More docs on Fine-tuning and Vector-DB assisted search will be cool

When you do Fine-tune, how do refer to the newly generated model in ./result dir ?

/Cant do much on my current 8GB RAM laptop, but will get soon one with GPU /

keep the good work..

**Comment by wanoz** [comment]
Thanks for the feedback! Yes we will definitely address those points and those are good ideas!

To load your already fine tuned model for usage again, simply do:
lm = ModelPack(model='./results/<model folder name>', source='local')

Let me know if there is any issues.
