### ISSUE TITLE
Error while loading model

### ISSUE THREAD

**Issue by Aaryanverma** [Pan-ML/panml#52]
Trained flan-t5-base model and getting error while trying to load from saved model location.

`OSError: Can't load tokenizer for './results/model_flan_3'. If you were trying to load it from 
'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make 
sure './results/model_flan_3' is the correct path to a directory containing all relevant files for a 
T5TokenizerFast tokenizer.`

**Comment by wanoz** [comment]
Thanks for catching this. This is being fixed with an active PR, the issue relates to tokenizer not set and saved properly.

**Comment by wanoz** [comment]
The latest patch v1.0.1 has been released for addressing this issue. Cheers.

**Comment by Aaryanverma** [comment]
Great!
